name: Example builds

on:
  push:
    branches: ['main', 'master', 'releases/*']
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        julia-version: ['1.0.5', '1', '^1.5.0-beta1']
        julia-arch: [x64, x86]
        os: [ubuntu-latest, macOS-latest, windows-latest]
        # 32-bit Julia binaries are not available on macOS
        exclude:
          - os: macOS-latest
            julia-arch: x86
    
    steps:
      - uses: actions/checkout@v1.0.0

      - name: "Install dependencies"
        run: |
          npm install
          npm run build
          npm run pack

      - run: mkdir -p ${{ github.workspace }}/dilumtestcache # TODO: delete this line
      - name: "Set up Julia"
        id: setup-julia
        uses: ./
        with:
          version: ${{ matrix.julia-version }}
          arch: ${{ matrix.julia-arch }}
        env:
           # TODO: delete this line
          RUNNER_TOOL_CACHE: ${{ github.workspace }}/dilumtestcache
      - run: which julia # TODO: delete this line
      - run: which -a julia # TODO: delete this line
      - run: julia --version
      - run: julia --compile=min -O0 -e 'import InteractiveUtils; InteractiveUtils.versioninfo()'
